name = "http-discord-bot"
type = "javascript"
account_id = ""

workers_dev = true

[vars]
PublicKey = ""                # Your client's public key
ClientID = ""                 # Your client's ID
Auth = "Bot YOUR_BOTS_TOKEN"  # The client's token
Version = "1.0.0"

#[[kv_namespaces]]
#binding = "KV"
#preview_id = ""
#id = ""